name: Publish to NuGet

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Pack
      run: dotnet pack --configuration Release --no-build --output ./artifacts

    - name: Publish to NuGet
      uses: nuget/setup-nuget@v1

    - name: Push to NuGet
      run: nuget push ./artifacts/*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate